### ISSUE TITLE
The mod don't take effect

### ISSUE THREAD

**Issue by ByrneShaw** [seymourimadeit/IllagersWearArmor#1]
I used forge-1.16.5-36.2.2

**Comment by seymourimadeit** [comment]
Could you elaborate on this? I'm testing it out right now on the same version and the illagers do seem to spawn with armor, unless the problem is with something else.

Also sorry for the late response.

**Comment by ByrneShaw** [comment]
> Could you elaborate on this? I'm testing it out right now on the same version and the illagers do seem to spawn with armor, unless the problem is with something else.
> 
> Also sorry for the late response.
> 
> One factor that could lead to illagers not appearing to wear armor would be if you have a resource pack that changes the illagers model (ie fresh animations), as this mod has to override their models.

I only installed this mod, not even optifine installed

**Comment by seymourimadeit** [comment]
Can you verify if the mod is installed correctly and if the game recognizes its existence? If it is, could you send your config files in a pastebin.  Also the version of the mod you have would help as well.

Also do you mean the illagers just don't spawn with armor at all or the mod just isn't recognized?

**Comment by ByrneShaw** [comment]
> Can you verify if the mod is installed correctly and if the game recognizes its existence? If it is, could you send your config files in a pastebin. Also the version of the mod you have would help as well.
> 
> Also do you mean the illagers just don't spawn with armor at all or the mod just isn't recognized?

is displayed in the mod list, but it does not take effect in the game.
forge version is 1.16.5-36.2.2
mod version is 1.0.4
As the above friend(Diycnel) said, it's not just me

**Comment by seymourimadeit** [comment]
Does the pillager spawned with this command 
`/summon pillager ~ ~ ~ {ArmorItems:[{},{},{},{id:"minecraft:iron_helmet",Count:1b}]}` render the iron helmet on hand?

**Comment by ByrneShaw** [comment]
> Does the pillager spawned with this command
> `/summon pillager ~ ~ ~ {ArmorItems:[{},{},{},{id:"minecraft:iron_helmet",Count:1b}]}` render the iron helmet? You could also try setting the chances for illagers to spawn with armor in raids to 1.00 (reset the config after testing) and seeing if they render any armor.
> 
> If either one works and the illagers render armor in either of those instances it most likely means you just have bad rng

Well, it's settled. So is this a configuration problem? The default configuration isn't enough for them to wear armor
