### ISSUE TITLE
Loot Table Crash during Raids

### ISSUE THREAD

**Issue by Lightman314** [seymourimadeit/IllagersWearArmor#10]
Game randomly crashes during raids.

Forge: 1.18.1-39.1.0
Version: illagersweararmor-1.1.2

[crash-2022-04-14_15.25.11-server.txt](https://github.com/seymourimadeit/IllagersWearArmor/files/8492090/crash-2022-04-14_15.25.11-server.txt)

**Comment by seymourimadeit** [comment]
You're gonna need to fully update to 1.18.2 tp get the bugfixed version of this mod as I don't support 1.18.1 anymore
