### ISSUE TITLE
1.18.2 - version 1.1.4 - Full crash related to illagers failing to spawn, repeatable 

### ISSUE THREAD

**Issue by ProvoGo** [seymourimadeit/IllagersWearArmor#11]
Server and Client crashes when illagers cant find a valid place to spawn. (i think) I have managed to repeat it by making a ''village'' at y 6 and started a raid there, the game never manages to actually spawn any illagers.

**Comment by seymourimadeit** [comment]
Please send the crash report.

**Comment by ProvoGo** [comment]
lol i completely forgot about the crash report xD guessing you dont need it now but just in case.
[crash-2022-04-16_17.19.24-server.txt](https://github.com/seymourimadeit/IllagersWearArmor/files/8500742/crash-2022-04-16_17.19.24-server.txt)
