### ISSUE TITLE
IWA has failed to load correctly

### ISSUE THREAD

**Issue by Ariostraza** [seymourimadeit/IllagersWearArmor#17]
1.19.3 forge 4.1.2
Illagers Wear Armor (zllagersweararmor) has failed to load correctly
java.lang.noSuchFieldError: THIS_ entity

Crash Report:
[[Link]](https://jpst.it/34xcl)

**Comment by seymourimadeit** [comment]
I am unable to recreate this issue when using the mod alone, could you try to see if another mod is conflicting with this mod?

**Comment by seymourimadeit** [comment]
Ok upon further investigation somehow I uploaded a broken version of the mod to cf (despite it not happening in any of my dev environments) so hopefully the reuploaded version will have the problem solved. Sorry for the troubles.

https://www.curseforge.com/minecraft/mc-mods/illagers-wear-armor/files/4351255
