### ISSUE TITLE
[1.16.5Forge] Illagers' legs are abnormal

### ISSUE THREAD

**Issue by GoldenTotem** [seymourimadeit/IllagersWearArmor#24]
Minecraft 1.16.5  Mod 1.0.5
This mod make some illagers' step bigger than vanilla. It means the angle of vindicator's two legs is bigger than before when they are walking. Some other illagers have this problem too.

**Comment by seymourimadeit** [comment]
Quite honestly this is such a minor issue that this is the rare time I'm gonna mark this as wontfix. Anyone however is free to make a pull request if this issue is really bothersome.
