### ISSUE TITLE
CRASH with enchant with mobs rendering

### ISSUE THREAD

**Issue by KaratFeng** [seymourimadeit/IllagersWearArmor#27]
the new enchant with mob crash with illager wear armor. I asked Bagu about this and she said that it was on your side to fix this. I would appreciate if you could fix this. thanks

[crash-2023-09-22_05.36.36-client.txt](https://github.com/seymourimadeit/IllagersWearArmor/files/12699559/crash-2023-09-22_05.36.36-client.txt)

**Comment by seymourimadeit** [comment]
hate to say it but i'm not gonna be updating 1.19.2 anymore; you're either going to have to downgrade your enchant with mobs or not have it altogether.
