### ISSUE TITLE
Placed feature crash?

### ISSUE THREAD

**Issue by Aceplante2** [seymourimadeit/IllagersWearArmor#28]
I was under the impression that your mod was a client side one that renders armor on illagers. So what "placed features" would there need to be?

Crash 1.20.1

**Comment by seymourimadeit** [comment]
Where’s the crash report

**Comment by Aceplante2** [comment]
I can get that later today

**Comment by Aceplante2** [comment]
Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Feature placement
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.m_214912_(ChunkMap.java:658)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)

**Comment by seymourimadeit** [comment]
please sned the whole thing, nothing much we can get from two lines
