### ISSUE TITLE
illagersweararmor-1.20-1.3.2 Crash On Launch

### ISSUE THREAD

**Issue by Tooop22** [seymourimadeit/IllagersWearArmor#31]
Launching Minecraft with illagersweararmor and no other mods installed crashes the game. To replicate just place illagersweararmor-1.20-1.3.2.jar in the mods folder and launch the game and it'll crash.

**Comment by seymourimadeit** [comment]
Please send the crash report for further diagnosis

**Comment by seymourimadeit** [comment]
OK I did the exact thing you said in this issue and literately no crash happens so I'm gonna have to close this issue for now until more info is provided
