### ISSUE TITLE
Conflict with Mana & Artifice

### ISSUE THREAD

**Issue by Mad-Gnome** [seymourimadeit/IllagersWearArmor#6]
Forge: 39.0.85
Version: Illagers wear armor 1.1.1 (worked fine with 1.1.0)
Version: Mana and Artifice 1.7.0.5 (current version as of posting this message)
 
When I update to 1.1.1 I receive a crash on startup, SP, with the message "Error: java.lang.IllegalStateException: Failed to load description for particle mna:arcane_random"

I realize this points to Mana and Artifice, but the two mods were compatible until your 1.1.1 update.  Posting this in M&A's Issue Tracker as well.

Full Crash Log: https://pastebin.com/ktJ63pn3

**Comment by Gaxon1** [comment]
Can confirm. I'm not even sure it's a conflict. I disabled every mod that was giving an error and a new error would pop up, I did this with 30 mods until I disabled Illagers and it started working again.
I reverted illagers Wear Armor to the previous version and everything works as it should.
